### ISSUE TITLE
Embedded templates on web player are not reporting display id and company id correctly

### ISSUE THREAD

**Issue by santiagonoguez** [Rise-Vision/rise-embedded-template#32]
If embedded templates are run in web player they are reporting displayId as 'preview' and companyId as null. This could be causing or contributing to malfunctions in embedded templates on web player and Android player.

This works well on player electron because an injected player configuration object exists there ( not available on web player ).
See [here](https://github.com/Rise-Vision/common-template/blob/master/src/rise-player-configuration.js#L223) and [here](https://github.com/Rise-Vision/common-template/blob/master/src/rise-player-configuration.js#L229).

The solution would be to provide those as parameters  ( 'cid' and 'id' respectively, as used in the functions linked above ) just as presentationId is provided, here:
https://github.com/Rise-Vision/rise-embedded-template/blob/master/src/rise-embedded-template.js#L112

FYI @tejohnso

**Comment by olegrise** [comment]
Fixed

**Comment by santiagonoguez** [comment]
Thanks @olegrise  !
